Match User xvault-upload
    ForceCommand /usr/bin/python3 /usr/local/libexec/xider-vault-upload/x_vault_transport.py receive
    AuthorizedKeysFile /etc/ssh/authorized_keys/%u
    AuthenticationMethods publickey
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    AllowTcpForwarding no
    AllowAgentForwarding no
    PermitTunnel no
    PermitTTY no
    X11Forwarding no
    PermitUserRC no
Match all
