@echo off
setlocal
cd /d "%~dp0"
title XGENT-WDS: Сборка EXE
echo ==========================================
echo   XGENT-WDS: сборка одного файла exe
echo ==========================================

:: 1. Закрываем любые работающие экземпляры, чтобы файл не был заблокирован
echo [..] Проверка и остановка запущенных процессов агента...
taskkill /F /IM XGENT-WDS.exe >nul 2>&1
taskkill /F /IM pythonw.exe >nul 2>&1

if not exist "venv\Scripts\python.exe" (
    echo [..] Создаю виртуальное окружение...
    python -m venv venv
)

echo [..] Установка зависимостей + PyInstaller...
venv\Scripts\python.exe -m pip install -q -r requirements.txt pyinstaller

echo [..] Вшиваю текущий .env в сборку (файл _secrets_embed.py)...
venv\Scripts\python.exe -c "from pathlib import Path; vals={}; [vals.setdefault(*l.strip().split('=',1)) for l in Path('.env').read_text(encoding='utf-8-sig').splitlines() if '=' in l and not l.strip().startswith('#')]; Path('_secrets_embed.py').write_text('# autogenerated by build_exe.bat - do not commit\nVALUES = ' + repr(vals) + '\n', encoding='utf-8'); print('embedded keys:', ', '.join(vals))"

echo [..] Компиляция PyInstaller (подождите 1-2 минуты)...
venv\Scripts\python.exe -m PyInstaller --onefile --noconsole --clean --noconfirm ^
  --name XGENT-WDS ^
  --collect-all soundfile ^
  --collect-all pyttsx3 ^
  --hidden-import pystray._win32 ^
  --hidden-import comtypes.stream ^
  xgent_wds.py

if errorlevel 1 (
    echo.
    echo [FAIL] Сборка не удалась - смотри ошибку выше.
    del _secrets_embed.py >nul 2>&1
    pause
    exit /b 1
)

del _secrets_embed.py >nul 2>&1

:: Копируем готовый exe в корень папки XGENT-WDS и в корень репозитория
copy /y "dist\XGENT-WDS.exe" "XGENT-WDS.exe" >nul 2>&1
copy /y "dist\XGENT-WDS.exe" "..\XGENT-WDS.exe" >nul 2>&1

echo.
echo ==========================================
echo [OK] Сборка успешно завершена!
echo ==========================================
echo Готовый файл скопирован в:
echo   1. XGENT-WDS\XGENT-WDS.exe
echo   2. Корень репозитория: XIDER\XGENT-WDS.exe
echo.
echo Это полностью автономный exe-файл со всеми 100 функциями.
echo Запусти его двойным кликом — он появится в трее и подключится к боту!
pause